
package com.avaya.xml.ws.systemmanagementservice._2008._07._01;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.avaya.xml.sms.ModelChoices;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SystemManagementPort", targetNamespace = "http://xml.avaya.com/ws/SystemManagementService/2008/07/01")
@XmlSeeAlso({
    com.avaya.xml.sms.ObjectFactory.class,
    com.avaya.xml.ws.session.ObjectFactory.class,
    com.avaya.xml.ws.systemmanagementservice._2008._07._01.ObjectFactory.class
})
public interface SystemManagementPort {


    /**
     * 
     * @param modelFields
     * @param qualifier
     * @param objectname
     * @param operation
     * @return
     *     returns com.avaya.xml.ws.systemmanagementservice._2008._07._01.Result
     */
    @WebMethod(action = "http://xml.avaya.com/ws/SystemManagementService/2008/07/01#soap_webservice#submitRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "submitRequest", targetNamespace = "http://xml.avaya.com/ws/SystemManagementService/2008/07/01", className = "com.avaya.xml.ws.systemmanagementservice._2008._07._01.SubmitRequestType")
    @ResponseWrapper(localName = "submitRequestResponse", targetNamespace = "http://xml.avaya.com/ws/SystemManagementService/2008/07/01", className = "com.avaya.xml.ws.systemmanagementservice._2008._07._01.ReturnType")
    public Result submitRequest(
        @WebParam(name = "modelFields", targetNamespace = "")
        ModelChoices modelFields,
        @WebParam(name = "operation", targetNamespace = "")
        String operation,
        @WebParam(name = "objectname", targetNamespace = "")
        String objectname,
        @WebParam(name = "qualifier", targetNamespace = "")
        String qualifier);

    /**
     * 
     * @param body
     * @return
     *     returns com.avaya.xml.ws.systemmanagementservice._2008._07._01.ReturnType
     */
    @WebMethod(action = "http://xml.avaya.com/ws/SystemManagementService/2008/07/01#soap_webservice#release")
    @WebResult(name = "releaseResponse", targetNamespace = "http://xml.avaya.com/ws/SystemManagementService/2008/07/01", partName = "return")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReturnType release(
        @WebParam(name = "release", targetNamespace = "http://xml.avaya.com/ws/SystemManagementService/2008/07/01", partName = "body")
        String body);

}
