
package com.avaya.xml.ws.systemmanagementservice._2008._07._01;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SystemManagementService", targetNamespace = "http://xml.avaya.com/ws/SystemManagementService/2008/07/01", wsdlLocation = "file:/Users/sanghyunlee/Library/CloudStorage/OneDrive-\uc774\uc528\uc5d0\uc2a4\ud154\ub808\ucf64/ECS/\ub0b4\ubd80\uad50\uc721/API%20\uc774\ud574\uc640%20\ud65c\uc6a9/2024\ub144/resource/wsdl/SystemManagementService.wsdl")
public class SystemManagementService
    extends Service
{

    private final static URL SYSTEMMANAGEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SYSTEMMANAGEMENTSERVICE_EXCEPTION;
    private final static QName SYSTEMMANAGEMENTSERVICE_QNAME = new QName("http://xml.avaya.com/ws/SystemManagementService/2008/07/01", "SystemManagementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/sanghyunlee/Library/CloudStorage/OneDrive-\uc774\uc528\uc5d0\uc2a4\ud154\ub808\ucf64/ECS/\ub0b4\ubd80\uad50\uc721/API%20\uc774\ud574\uc640%20\ud65c\uc6a9/2024\ub144/resource/wsdl/SystemManagementService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SYSTEMMANAGEMENTSERVICE_WSDL_LOCATION = url;
        SYSTEMMANAGEMENTSERVICE_EXCEPTION = e;
    }

    public SystemManagementService() {
        super(__getWsdlLocation(), SYSTEMMANAGEMENTSERVICE_QNAME);
    }

    public SystemManagementService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SYSTEMMANAGEMENTSERVICE_QNAME, features);
    }

    public SystemManagementService(URL wsdlLocation) {
        super(wsdlLocation, SYSTEMMANAGEMENTSERVICE_QNAME);
    }

    public SystemManagementService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SYSTEMMANAGEMENTSERVICE_QNAME, features);
    }

    public SystemManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SystemManagementService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SystemManagementPort
     */
    @WebEndpoint(name = "SystemManagementPort")
    public SystemManagementPort getSystemManagementPort() {
        return super.getPort(new QName("http://xml.avaya.com/ws/SystemManagementService/2008/07/01", "SystemManagementPort"), SystemManagementPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SystemManagementPort
     */
    @WebEndpoint(name = "SystemManagementPort")
    public SystemManagementPort getSystemManagementPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xml.avaya.com/ws/SystemManagementService/2008/07/01", "SystemManagementPort"), SystemManagementPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SYSTEMMANAGEMENTSERVICE_EXCEPTION!= null) {
            throw SYSTEMMANAGEMENTSERVICE_EXCEPTION;
        }
        return SYSTEMMANAGEMENTSERVICE_WSDL_LOCATION;
    }

}
